// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubjmbckferfqwcwugbgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViam1iY2tmZXJmcXdjd3VnYmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3ODI5ODAsImV4cCI6MjA1ODM1ODk4MH0.QSv69KxodspIIX8lq24hn3I2ylxXQ9yoQ-3B9qxMJ84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);